USE productdb;
ALTER TABLE products ADD COLUMN category VARCHAR(80) NOT NULL DEFAULT 'Khác' AFTER name;
CREATE TABLE IF NOT EXISTS categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);
